//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.twitterCloneService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tweet", Namespace="http://schemas.datacontract.org/2004/07/TwitterCloneProjectv1._4")]
    [System.SerializableAttribute()]
    public partial class Tweet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> favoriSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciNickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tweetIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tweetTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> favoriSayisi {
            get {
                return this.favoriSayisiField;
            }
            set {
                if ((this.favoriSayisiField.Equals(value) != true)) {
                    this.favoriSayisiField = value;
                    this.RaisePropertyChanged("favoriSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciID {
            get {
                return this.kullaniciIDField;
            }
            set {
                if ((this.kullaniciIDField.Equals(value) != true)) {
                    this.kullaniciIDField = value;
                    this.RaisePropertyChanged("kullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kullaniciNick {
            get {
                return this.kullaniciNickField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciNickField, value) != true)) {
                    this.kullaniciNickField = value;
                    this.RaisePropertyChanged("kullaniciNick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tarih {
            get {
                return this.tarihField;
            }
            set {
                if ((this.tarihField.Equals(value) != true)) {
                    this.tarihField = value;
                    this.RaisePropertyChanged("tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tweetID {
            get {
                return this.tweetIDField;
            }
            set {
                if ((this.tweetIDField.Equals(value) != true)) {
                    this.tweetIDField = value;
                    this.RaisePropertyChanged("tweetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tweetText {
            get {
                return this.tweetTextField;
            }
            set {
                if ((object.ReferenceEquals(this.tweetTextField, value) != true)) {
                    this.tweetTextField = value;
                    this.RaisePropertyChanged("tweetText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kullanici", Namespace="http://schemas.datacontract.org/2004/07/TwitterCloneProjectv1._4")]
    [System.SerializableAttribute()]
    public partial class kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciNickField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciID {
            get {
                return this.kullaniciIDField;
            }
            set {
                if ((this.kullaniciIDField.Equals(value) != true)) {
                    this.kullaniciIDField = value;
                    this.RaisePropertyChanged("kullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kullaniciNick {
            get {
                return this.kullaniciNickField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciNickField, value) != true)) {
                    this.kullaniciNickField = value;
                    this.RaisePropertyChanged("kullaniciNick");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="twitterCloneService.ITwitterCloneService")]
    public interface ITwitterCloneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/UyeOl", ReplyAction="http://tempuri.org/ITwitterCloneService/UyeOlResponse")]
        bool UyeOl(string ad, string soyad, bool cinsiyet, System.DateTime dogumTarihi, string mail, string password, string Nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/UyeOl", ReplyAction="http://tempuri.org/ITwitterCloneService/UyeOlResponse")]
        System.Threading.Tasks.Task<bool> UyeOlAsync(string ad, string soyad, bool cinsiyet, System.DateTime dogumTarihi, string mail, string password, string Nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TweetAt", ReplyAction="http://tempuri.org/ITwitterCloneService/TweetAtResponse")]
        bool TweetAt(int ID, string tweetText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TweetAt", ReplyAction="http://tempuri.org/ITwitterCloneService/TweetAtResponse")]
        System.Threading.Tasks.Task<bool> TweetAtAsync(int ID, string tweetText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TweetleriGoruntule", ReplyAction="http://tempuri.org/ITwitterCloneService/TweetleriGoruntuleResponse")]
        WebApplication8.twitterCloneService.Tweet[] TweetleriGoruntule(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TweetleriGoruntule", ReplyAction="http://tempuri.org/ITwitterCloneService/TweetleriGoruntuleResponse")]
        System.Threading.Tasks.Task<WebApplication8.twitterCloneService.Tweet[]> TweetleriGoruntuleAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/FavorilereEkle", ReplyAction="http://tempuri.org/ITwitterCloneService/FavorilereEkleResponse")]
        bool FavorilereEkle(int ID, int TweetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/FavorilereEkle", ReplyAction="http://tempuri.org/ITwitterCloneService/FavorilereEkleResponse")]
        System.Threading.Tasks.Task<bool> FavorilereEkleAsync(int ID, int TweetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/Login", ReplyAction="http://tempuri.org/ITwitterCloneService/LoginResponse")]
        int Login(string Nick, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/Login", ReplyAction="http://tempuri.org/ITwitterCloneService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string Nick, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/Update", ReplyAction="http://tempuri.org/ITwitterCloneService/UpdateResponse")]
        bool Update(int kullaniciID, string ad, string soyad, bool cinsiyet, System.DateTime dts, string mail, string password, string Nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/Update", ReplyAction="http://tempuri.org/ITwitterCloneService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(int kullaniciID, string ad, string soyad, bool cinsiyet, System.DateTime dts, string mail, string password, string Nick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TakipEt", ReplyAction="http://tempuri.org/ITwitterCloneService/TakipEtResponse")]
        bool TakipEt(int takipciID, int takipEdilenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TakipEt", ReplyAction="http://tempuri.org/ITwitterCloneService/TakipEtResponse")]
        System.Threading.Tasks.Task<bool> TakipEtAsync(int takipciID, int takipEdilenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TakipBirak", ReplyAction="http://tempuri.org/ITwitterCloneService/TakipBirakResponse")]
        bool TakipBirak(int takipciID, int takipEdilenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TakipBirak", ReplyAction="http://tempuri.org/ITwitterCloneService/TakipBirakResponse")]
        System.Threading.Tasks.Task<bool> TakipBirakAsync(int takipciID, int takipEdilenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TweetSil", ReplyAction="http://tempuri.org/ITwitterCloneService/TweetSilResponse")]
        bool TweetSil(int tweetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TweetSil", ReplyAction="http://tempuri.org/ITwitterCloneService/TweetSilResponse")]
        System.Threading.Tasks.Task<bool> TweetSilAsync(int tweetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TakipcilerGetir", ReplyAction="http://tempuri.org/ITwitterCloneService/TakipcilerGetirResponse")]
        WebApplication8.twitterCloneService.kullanici[] TakipcilerGetir(int takipciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/TakipcilerGetir", ReplyAction="http://tempuri.org/ITwitterCloneService/TakipcilerGetirResponse")]
        System.Threading.Tasks.Task<WebApplication8.twitterCloneService.kullanici[]> TakipcilerGetirAsync(int takipciID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/kullanicilariGoster", ReplyAction="http://tempuri.org/ITwitterCloneService/kullanicilariGosterResponse")]
        WebApplication8.twitterCloneService.kullanici[] kullanicilariGoster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/kullanicilariGoster", ReplyAction="http://tempuri.org/ITwitterCloneService/kullanicilariGosterResponse")]
        System.Threading.Tasks.Task<WebApplication8.twitterCloneService.kullanici[]> kullanicilariGosterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/KullaniciTweetleri", ReplyAction="http://tempuri.org/ITwitterCloneService/KullaniciTweetleriResponse")]
        WebApplication8.twitterCloneService.Tweet[] KullaniciTweetleri(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterCloneService/KullaniciTweetleri", ReplyAction="http://tempuri.org/ITwitterCloneService/KullaniciTweetleriResponse")]
        System.Threading.Tasks.Task<WebApplication8.twitterCloneService.Tweet[]> KullaniciTweetleriAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITwitterCloneServiceChannel : WebApplication8.twitterCloneService.ITwitterCloneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TwitterCloneServiceClient : System.ServiceModel.ClientBase<WebApplication8.twitterCloneService.ITwitterCloneService>, WebApplication8.twitterCloneService.ITwitterCloneService {
        
        public TwitterCloneServiceClient() {
        }
        
        public TwitterCloneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TwitterCloneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterCloneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TwitterCloneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UyeOl(string ad, string soyad, bool cinsiyet, System.DateTime dogumTarihi, string mail, string password, string Nick) {
            return base.Channel.UyeOl(ad, soyad, cinsiyet, dogumTarihi, mail, password, Nick);
        }
        
        public System.Threading.Tasks.Task<bool> UyeOlAsync(string ad, string soyad, bool cinsiyet, System.DateTime dogumTarihi, string mail, string password, string Nick) {
            return base.Channel.UyeOlAsync(ad, soyad, cinsiyet, dogumTarihi, mail, password, Nick);
        }
        
        public bool TweetAt(int ID, string tweetText) {
            return base.Channel.TweetAt(ID, tweetText);
        }
        
        public System.Threading.Tasks.Task<bool> TweetAtAsync(int ID, string tweetText) {
            return base.Channel.TweetAtAsync(ID, tweetText);
        }
        
        public WebApplication8.twitterCloneService.Tweet[] TweetleriGoruntule(int ID) {
            return base.Channel.TweetleriGoruntule(ID);
        }
        
        public System.Threading.Tasks.Task<WebApplication8.twitterCloneService.Tweet[]> TweetleriGoruntuleAsync(int ID) {
            return base.Channel.TweetleriGoruntuleAsync(ID);
        }
        
        public bool FavorilereEkle(int ID, int TweetID) {
            return base.Channel.FavorilereEkle(ID, TweetID);
        }
        
        public System.Threading.Tasks.Task<bool> FavorilereEkleAsync(int ID, int TweetID) {
            return base.Channel.FavorilereEkleAsync(ID, TweetID);
        }
        
        public int Login(string Nick, string password) {
            return base.Channel.Login(Nick, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string Nick, string password) {
            return base.Channel.LoginAsync(Nick, password);
        }
        
        public bool Update(int kullaniciID, string ad, string soyad, bool cinsiyet, System.DateTime dts, string mail, string password, string Nick) {
            return base.Channel.Update(kullaniciID, ad, soyad, cinsiyet, dts, mail, password, Nick);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(int kullaniciID, string ad, string soyad, bool cinsiyet, System.DateTime dts, string mail, string password, string Nick) {
            return base.Channel.UpdateAsync(kullaniciID, ad, soyad, cinsiyet, dts, mail, password, Nick);
        }
        
        public bool TakipEt(int takipciID, int takipEdilenID) {
            return base.Channel.TakipEt(takipciID, takipEdilenID);
        }
        
        public System.Threading.Tasks.Task<bool> TakipEtAsync(int takipciID, int takipEdilenID) {
            return base.Channel.TakipEtAsync(takipciID, takipEdilenID);
        }
        
        public bool TakipBirak(int takipciID, int takipEdilenID) {
            return base.Channel.TakipBirak(takipciID, takipEdilenID);
        }
        
        public System.Threading.Tasks.Task<bool> TakipBirakAsync(int takipciID, int takipEdilenID) {
            return base.Channel.TakipBirakAsync(takipciID, takipEdilenID);
        }
        
        public bool TweetSil(int tweetID) {
            return base.Channel.TweetSil(tweetID);
        }
        
        public System.Threading.Tasks.Task<bool> TweetSilAsync(int tweetID) {
            return base.Channel.TweetSilAsync(tweetID);
        }
        
        public WebApplication8.twitterCloneService.kullanici[] TakipcilerGetir(int takipciID) {
            return base.Channel.TakipcilerGetir(takipciID);
        }
        
        public System.Threading.Tasks.Task<WebApplication8.twitterCloneService.kullanici[]> TakipcilerGetirAsync(int takipciID) {
            return base.Channel.TakipcilerGetirAsync(takipciID);
        }
        
        public WebApplication8.twitterCloneService.kullanici[] kullanicilariGoster() {
            return base.Channel.kullanicilariGoster();
        }
        
        public System.Threading.Tasks.Task<WebApplication8.twitterCloneService.kullanici[]> kullanicilariGosterAsync() {
            return base.Channel.kullanicilariGosterAsync();
        }
        
        public WebApplication8.twitterCloneService.Tweet[] KullaniciTweetleri(int ID) {
            return base.Channel.KullaniciTweetleri(ID);
        }
        
        public System.Threading.Tasks.Task<WebApplication8.twitterCloneService.Tweet[]> KullaniciTweetleriAsync(int ID) {
            return base.Channel.KullaniciTweetleriAsync(ID);
        }
    }
}
